### ISSUE TITLE
A question about the test code

### ISSUE THREAD

**Issue by MinglangQiao** [wusonghe/TMFI-Net#3]
Hi, thanks for sharing your nice work! It seems that there is a  small issue in the test code. In line51 of [here](https://github.com/wusonghe/TMFI-Net/blob/cfe49c52724c53990d0717af8324ad7e203eba43/test_DHF1K.py#L51C27-L51C27),  list_frames.sort() will not arrange the frames by numbers like "0.png, 1.png, 2.png, 3.png, .... ". Instead, list_frames.sort() results in "0.png, 1.png, 10.png, 100.png, ... ". It may have some negative impact on the result,  could you please check this?

**Comment by wusonghe** [comment]
Hello, thank you for your interest in this paper. Regarding the problem you mentioned, you can run the following code. The picture names of the DHF1K dataset are all four digits, so they can be sorted normally.

words = ['1', '2', '10']  # 字符串长度不同时
words.sort()
print(words)
# ['1', '10', '2']

words = ['001', '002', '010']  # 字符串长度相同时
words.sort()
print(words)
# ['001', '002', '010']

**Comment by MinglangQiao** [comment]
I get it, thanks for your reply!
